### ISSUE TITLE
Suggestion: Move discussion threads to /welcome repo

### ISSUE THREAD

**Issue by aphelionz** [rs-ipfs/rust-ipfs#139]
I'm wondering if we can consolidate these [discussions](https://github.com/ipfs-rust/rust-ipfs/issues?q=is%3Aopen+is%3Aissue+label%3Adiscussion) by moving them to the [welcome](https://github.com/ipfs-rust/welcome) repo, giving more space to tech-related issues in `rust-ipfs` proper? We can still reference them and link to them, and I can call out this distinction early in the README files of both repos.

Alternatively, I could create a new org-wide public project that contains all of the items tagged discussion across all the variate repos.

**Comment by aphelionz** [comment]
These are the current candidates for transfer: https://github.com/rs-ipfs/rust-ipfs/issues?q=is%3Aopen+is%3Aissue+label%3Adiscussion

Any omissions and/or things that shouldn't be included?

**Comment by koivunej** [comment]
#146, #141: Can be archived as is. These are already handled in the bitswap crate if we can upgrade to that at some point. Material in #94 is pretty much present in code already as FIXMEs, TODOs, so that could be closed/archived as well.

Not sure if anyone wants to discuss the processes #59. I think the scoping is good issue to have but that can be in welcome as you proposed #57. I should probably refreshen that up as well.

#125 is something I'd like to keep since trying it out wouldn't be a too long operation. Not committing to supporting full ssh-keygen format without having read up on it but working towards an external identity file, that is :) I should update the issue.

**Comment by aphelionz** [comment]
Great. I've transferred the issues and left the others as is. This can be closed.
