### ISSUE TITLE
[BUG] /usr/bin/ld: cannot find -lz

### ISSUE THREAD

**Issue by aphelionz** [rs-ipfs/rust-ipfs#217]
**Describe the bug**
When compiling on a fairly fresh Debian Sid instance, I got the following error upon installation: 

```
/usr/bin/ld: cannot find -lz
```

Installing `zlib1g-dev` fixes it. I'd like to add something to the README's installation dependencies to this effect, but wanted to open this issue for feedback first.

**Comment by koivunej** [comment]
Good find. This is seems to be at least because of:

```
$ cargo tree
ipfs v0.1.0 (...)
| ...
├── libp2p v0.20.1
| ...
│   ├── libp2p-deflate v0.19.2
│   │   ├── flate2 v1.0.16
│   │   │   ├── cfg-if v0.1.10
│   │   │   ├── crc32fast v1.2.0
│   │   │   │   └── cfg-if v0.1.10
│   │   │   ├── libc v0.2.67
│   │   │   ├── libz-sys v1.0.25
```

Doing `cargo update -p flate2` does not solve this. I can't really see why, or because of which feature, the zlib dependency comes along, perhaps not enough coffee. I think this could be documented in the Cargo.toml as well..

Saying "at least because of" because we may have other less visible dependencies on zlib. I am thinking openssl but I guess it was needed openssl would come with some vendored zlib implementation.
